/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.io.File;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    static Window window;
    static File resourceDirectory;

        
    @Override
    public void start(Stage stage) throws Exception {
        window = new Window(stage);
    }

    public static void main(String[] args) {
        launch(args);
    }

}
